'\" t
.\"     Title: gccontrol
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2006-08-06
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "GCCONTROL" "1" "2006\-08\-06" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gccontrol \- GUI for ccontrol
.SH "SYNOPSIS"
.PP
The
\fBgccontrol\fR
command takes no arguments\&.
.SH "DESCRIPTION"
.PP
\fBgccontrol\fR
provides a Graphical User Interface for choosing the configuration file for
\fBccontrol\fR
to use\&. It works by switching the\ \&
\fB$HOME\fR/\&.ccontrol/config
symlink to point to another configuration file in that directory\&.
.SH "SEE ALSO"
.PP
ccontrol(1), ccontrol\-init(1)\&.
.SH "AUTHOR"
.PP
This manual page was written by
Ted
Percival
<ted@midg3t\&.net>
for the Debian system (but may be used by others)\&. Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 2 any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common\-licenses/GPL\&.
.SH "COPYRIGHT"
.br
Copyright \(co 2006 Ted Percival
.br
